# Generated by Django 4.0.3 on 2022-03-15 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_savingsaccounts_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditAccounts',
            new_name='CreditAccount',
        ),
        migrations.RenameModel(
            old_name='SavingsAccounts',
            new_name='SavingsAccount',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
