# Generated by Django 4.0.3 on 2022-03-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_id',
        ),
    ]
