# Generated by Django 4.0.3 on 2022-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_transaction_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.IntegerField(default=-1),
        ),
    ]
