# Generated by Django 4.0.3 on 2022-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaction_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditaccount',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='savingsaccount',
            old_name='amount',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
